Create db backups

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -31,17 +31,18 @@ go test -race -cover ./...
 # Send to servers.
 for s in 139.162.153.248; do
 	# Make backup so we can easily roll back if needed.
+	# TODO: cleanup older files.
 	ssh -p9012 "$s" cp "$name" "$name.$(date +%Y-%m-%dT%H:%M:%S)"
 
 	scp -P9012 "$name" "scp://$s/"
-	sum1=$(sha256sum "$name")
-	sum2=$(ssh -p9012 "$s" sha256sum "$name")
+	suml=$(sha256sum "$name")
+	sumr=$(ssh -p9012 "$s" sha256sum "$name")
 	rm "$name"
 
-	if [ "$sum1" != "$sum2" ]; then
+	if [ "$suml" != "$sumr" ]; then
 		echo >&2 "checksums don't match:"
-		echo >&2 "  local:  $sum1"
-		echo >&2 "  remote: $sum1"
+		echo >&2 "  local:  $suml"
+		echo >&2 "  remote: $sumr"
 		exit 1
 	fi
 done
