Many updates

diff --git a/etc/init.d/hitch b/etc/init.d/hitch
--- a/etc/init.d/hitch
+++ b/etc/init.d/hitch
@@ -1,43 +1,52 @@
 #!/sbin/openrc-run
 
 # setcap cap_net_bind_service=+ep hitch
-name="Hitch proxy"
+description="Hitch TLS proxy"
+description_checkconfig="Verify configuration file"
+description_reload="Reload configuration"
+
+extra_commands="checkconfig"
+extra_started_commands="reload"
+
 command="/usr/sbin/hitch"
 command_args="-p /var/run/hitch.pid --daemon ${HITCH_OPTS}"
 pidfile="/var/run/hitch.pid"
 
 depend() {
-        need net localmount
-        after firewall
+	need net localmount
+	after firewall
 }
 
 configtest() {
-        ebegin "Checking ${SVCNAME} configuration"
-        checkconfig
-        eend $?
+	ebegin "Checking ${SVCNAME} configuration"
+	checkconfig
+	eend $?
 }
 
 checkconfig() {
-        hitch -t $HITCH_OPTS >/dev/null 2>&1
-        ret=$?
-        if [ $ret -ne 0 ]; then
-                eerror "${SVCNAME} has detected an error in your setup:"
-                hitch -t $HITCH_OPTS
-        fi
+	hitch -t $HITCH_OPTS >/dev/null 2>&1
+	ret=$?
+	if [ $ret -ne 0 ]; then
+		eerror "${SVCNAME} has detected an error in your setup:"
+		hitch -t $HITCH_OPTS
+	fi
 
-        return $ret
+	return $ret
 }
 
 start_pre() {
-        checkconfig || return 1
+	checkconfig || return 1
 }
 
 stop_pre() {
-        if [ "${RC_CMD}" = "restart" ]; then
-                checkconfig || return 1
-        fi
+	if [ "${RC_CMD}" = "restart" ]; then
+		checkconfig || return 1
+	fi
 }
 
-# TODO: kill -HUP
-# reload() {
-# }
+reload() {
+	checkconfig || return 1
+	ebegin "Reloading $RC_SVCNAME"
+	start-stop-daemon --signal HUP --exec "$command" --pidfile "$pidfile"
+	eend $?
+}
